services:
  lucos_backups:
    build: .
    container_name: lucos_backups
    image: lucas42/lucos_backups:${VERSION:-latest}
    ports:
      - $PORT:$PORT
    environment:
      - SYSTEM
      - ENVIRONMENT
      - APP_ORIGIN
      - PORT
      - SSH_PRIVATE_KEY
      - GITHUB_KEY
      - SCHEDULE_TRACKER_ENDPOINT
      - LOGANNE_ENDPOINT
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 180s
    restart: always
    network_mode: host
